# -*- coding: utf-8 -*-
"""ejercicio1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/asalber/aprendeconalf/blob/master/content/es/docencia/python/ejercicios/soluciones/tipos-datos/ejercicio1.ipynb

## Ejercicio
Escribir un programa que muestre por pantalla la frase `¡Hola mundo!`

## Solución
"""

print("¡Hola Mundo!")