# -*- coding: utf-8 -*-
"""ejercicio3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/asalber/aprendeconalf/blob/master/content/es/docencia/python/ejercicios/soluciones/tipos-datos/ejercicio3.ipynb

## Ejercicio
Escribir un programa que pregunte el nombre del usuario en la consola y después de que el usuario lo introduzca muestre por pantalla la cadena `¡Hola <nombre>!`, donde `<nombre>` es el nombre que el usuario haya introducido.

## Solución
"""

nombre = input("Introduce tu nombre: ")
print("¡Hola " + nombre + "!")